### PR TITLE
Add quick start

### PR DESCRIPTION
**Pull request by trkw**
# Task 
- [x] Add quick start document
- [x] Add ignore vendor bundle

### CODE REVIEW

**Comment by trkw** [comment]
Deploy preview ready!

Built with commit 8d298a5c27efdc21bc83cabcb6ce0d7dcff1e9fa

https://deploy-preview-24--soussune.netlify.com

**Comment by miyaoka** [comment]
👍

**Review by miyaoka — DISMISSED** [review]
test

**Review by miyaoka — APPROVED** [review]
よいのでは

**Pull request merged**
